# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 010dcdc061f26667c8eae3cfb2778b1b88b6a032436d62d9fdb77e8850ee67417a0e1f7b90878be2a60f249aee118e4936d8785dcc96ddcb666348760861d644

test:
  secret_key_base: 8eeb83ed000761be496727354221beca9558d87c24af5aca319d9cf18143a61d42ff08b3e7b18c0f0fed612185bf4be123d5d04b9150a7e25520f7bb363d5eda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
